### ISSUE TITLE
why are you using 2 checks in the while loop

### ISSUE THREAD

**Issue by ChaymaeHarfoush** [emirot/codefights#12]
Could you tell me why are  you using 2 checks in the while loop condition
and why when I remove l from (while l and l.value == k) to be (while l.value==k) I got the following error?
'NoneType' object has no attribute 'value'

**Comment by emirot** [comment]
@ChaymaeHarfoush  which challenge are you talking about ?

**Comment by ChaymaeHarfoush** [comment]
@emirot Oh I thought that I 'm commenting  on the code itself,
 I'm talking about "RemoveFromList" code fights challenge

**Comment by emirot** [comment]
@ChaymaeHarfoush  The error you get is because your on the last node which is None and doesn't contain a value. The end of a linked list is marked by a Null node at the end. So you got a Null Pointer exception .
