### ISSUE TITLE
Strings Rearrangement doesn't work

### ISSUE THREAD

**Issue by lozaeric** [emirot/codefights#2]
Hi, I submitted your code but it didn't work.  I guess the tests have changed. 

greetings

 [https://github.com/emirot/codefights/blob/master/intro/stringsRearrangement.py](url)

**Comment by emirot** [comment]
Thanks @lozaeric I will take a look

**Comment by emirot** [comment]
@lozaeric  I've fixed it. https://github.com/emirot/codefights/commit/58d15767e678ef1697635069288943a0f6109305
